# -*- coding: utf-8 -*-
"""LogosticRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke26VnT79U0Udrlv2FSakhvNfNkqsXHc
"""

!pip install opendatasets --upgrade --quiet

import opendatasets as od

od.version()

dataset_url='https://www.kaggle.com/datasets/jsphyg/weather-dataset-rattle-package'

od.download(dataset_url)





import os

data_dir='./weather-dataset-rattle-package'

os.listdir(data_dir)

train_csv=data_dir+'/weatherAUS.csv'

train_csv

!pip install pandas  --quiet

import pandas as pd

raw_df=pd.read_csv(train_csv)

raw_df

raw_df.info()

raw_df.dropna(subset=['RainToday','RainTomorrow'],inplace=True)

raw_df.info()

!pip install plotly matplotlib seaborn --quiet

# Commented out IPython magic to ensure Python compatibility.
import plotly.express as px
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (10, 6)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

raw_df.Location.nunique()

import plotly.express as px

px.histogram(raw_df, x='Location', title='Location vs Rainy Days', color='RainToday')

px.histogram(raw_df,x='Temp3pm',title='Temparature at 3am vs. Rain Tmorrow',color='RainTomorrow')

px.histogram(raw_df,x='RainTomorrow',title='Raintmr .vs Rain today',color='RainToday')

px.scatter(raw_df .sample(2000),
          title='MIN Temp  vs.Max Temp.',
           x='MinTemp',
           y='MaxTemp',
           color='RainToday')

px.strip(raw_df.sample(2000),
         x='Temp3pm',
         y='Humidity3pm',
         title='Temp3pm vs.Humidity(3pm)',
         color='RainTomorrow',)

!pip install jovian --upgrade --quiet

import jovian

jovian.commit()

from sklearn.model_selection import train_test_split

train_val_df,test_df=train_test_split(raw_df,test_size=0.2,random_state=42)
train_df,val_df=train_test_split(train_val_df,test_size=0.25,random_state=42)

print('tarin_df.shape:',train_df.shape)
print('val_df:',val_df.shape)
print('test_df:',test_df.shape)

plt.title('No of rows per year')
sns.countplot(x=pd.to_datetime(raw_df.Date).dt.year);

year=pd.to_datetime(raw_df.Date).dt.year


tarin_df = raw_df[year<2015]
val_df=raw_df[year==2015]
test_df=raw_df[year>2015]

print('tarin_df.shape:',train_df)
print('val_df:',val_df)
print('test_df:',test_df)

train_df

val_df

test_df

jovian.commit()

input_cols=list(train_df.columns)[1:-1]
target_col='RainTomorrow'

print(input_cols)

target_col

train_inputs=train_df[input_cols].copy()
train_targets=tarin_df[target_col].copy()

val_inputs=val_df[input_cols].copy()
val_targets=val_df[target_col].copy()

test_inputs=test_df[input_cols].copy()
test_targets=test_df[target_col].copy()

train_inputs

type(train_targets)

!pip install numpy --quiet

import numpy as np

numeric_cols=train_inputs.select_dtypes(include=np.number).columns.tolist()[:-1]
categorical_cols=train_inputs.select_dtypes('object').columns.tolist()

numeric_cols

train_inputs[numeric_cols].describe()

train_inputs[categorical_cols].nunique()

jovian.commit()

from sklearn.impute import SimpleImputer

imputer =SimpleImputer(strategy='mean')

raw_df[numeric_cols].isna().sum()

train_inputs[numeric_cols].isna().sum()

raw_df[numeric_cols]

imputer.fit(raw_df[numeric_cols])

print(numeric_cols)

list(imputer.statistics_)

imputer.transform(train_inputs[numeric_cols])

train_inputs[numeric_cols]=imputer.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols]=imputer.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols]=imputer.transform(test_inputs[numeric_cols])

train_inputs[numeric_cols].isna().sum()

raw_df[numeric_cols].describe()

from sklearn.preprocessing import MinMaxScaler

?MinMaxScaler()#we can inspect the minimum and maximum values in each column

scaler=MinMaxScaler()

scaler.fit(raw_df[numeric_cols])

print('Minimum:')
list(scaler.data_min_)

print('Minimum:')
list(scaler.data_max_)

train_inputs[numeric_cols]=scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols]=scaler.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols]=scaler.transform(test_inputs[numeric_cols])



train_inputs[numeric_cols].describe()

jovian.commit()

raw_df.Location.unique()

raw_df[categorical_cols].nunique()

from sklearn.preprocessing import OneHotEncoder

?OneHotEncoder

encoder=OneHotEncoder(sparse_output=False,handle_unknown='ignore')

encoder.fit(raw_df[categorical_cols])

encoder.categories_

encoded_cols=list(encoder.get_feature_names_out(categorical_cols))
print(encoded_cols)

train_inputs[encoded_cols]=encoder.transform(train_inputs[categorical_cols])
val_inputs[encoded_cols]=encoder.transform(val_inputs[categorical_cols])
test_inputs[encoded_cols]=encoder.transform(test_inputs[categorical_cols])

pd.set_option('display.max_columns',None)

test_inputs

jovian.commit()

#trainiinng large Regression model
print('train_inputs:',train_inputs.shape)
print('train_inputs:',train_targets.shape)
print('val_inputs:',val_inputs.shape)
print('val_targets:',val_targets.shape)
print('test_inputs:',test_inputs.shape)
print('test_targets:',test_targets.shape)

!pip install pyarrow --quiet

train_inputs.to_parquet('train_inputs.parquet')
val_inputs.to_parquet('val_iputs.parquet')
test_inputs.to_parquet('test_inputs.parquet')

# Commented out IPython magic to ensure Python compatibility.
#  %%time
 pd.DataFrame(train_targets).to_parquet('train_targets.parquet')
 pd.DataFrame(val_targets).to_parquet('val_targets.parquet')
 pd.DataFrame(test_targets).to_parquet('test_targets.parquet')

train_inputs#just to check the categorical_data

from sklearn.linear_model import LogisticRegression
model=LogisticRegression(solver='liblinear')

?LogisticRegression

import pandas as pd

df = pd.concat([train_inputs, train_targets], axis=1)

df = df.dropna()

train_inputs = df[numeric_cols + encoded_cols]
train_targets = df[train_targets.name]   # or column name

model.fit(train_inputs[numeric_cols + encoded_cols],train_targets)

model.fit(train_inputs[numeric_cols + encoded_cols], train_targets)

print(numeric_cols + encoded_cols)

print(model.coef_.tolist())

print(model.intercept_)

X_train = train_inputs[numeric_cols + encoded_cols]
X_val = val_inputs[numeric_cols + encoded_cols]
X_test = test_inputs[numeric_cols + encoded_cols]

train_preds = model.predict(X_train)

train_preds

train_targets

train_probs = model.predict_proba(X_train)
train_probs

model.classes_

from sklearn.metrics import accuracy_score

accuracy_score(train_targets, train_preds)

from sklearn.metrics import confusion_matrix

confusion_matrix(train_targets, train_preds, normalize='true')

def predict_and_plot(inputs, targets, name=''):
    preds = model.predict(inputs)

    accuracy = accuracy_score(targets, preds)
    print("Accuracy: {:.2f}%".format(accuracy * 100))

    cf = confusion_matrix(targets, preds, normalize='true')
    plt.figure()
    sns.heatmap(cf, annot=True)
    plt.xlabel('Prediction')
    plt.ylabel('Target')
    plt.title('{} Confusion Matrix'.format(name));

    return preds

train_preds = predict_and_plot(X_train, train_targets, 'Training')

val_preds=predict_and_plot(X_val,val_targets,'Validation')

test_preds=predict_and_plot(X_test,test_targets,'Test')

def random_guess(inputs):
    return np.random.choice(["No", "Yes"], len(inputs))

def all_no(inputs):
    return np.full(len(inputs), "No")

accuracy_score(test_targets, random_guess(X_test))

accuracy_score(test_targets,all_no(X_test))

jovian.commit()

new_input = {'Date': '2021-06-19',
             'Location': 'Katherine',
             'MinTemp': 23.2,
             'MaxTemp': 33.2,
             'Rainfall': 10.2,
             'Evaporation': 4.2,
             'Sunshine': np.nan,
             'WindGustDir': 'NNW',
             'WindGustSpeed': 52.0,
             'WindDir9am': 'NW',
             'WindDir3pm': 'NNE',
             'WindSpeed9am': 13.0,
             'WindSpeed3pm': 20.0,
             'Humidity9am': 89.0,
             'Humidity3pm': 58.0,
             'Pressure9am': 1004.8,
             'Pressure3pm': 1001.5,
             'Cloud9am': 8.0,
             'Cloud3pm': 5.0,
             'Temp9am': 25.7,
             'Temp3pm': 33.0,
             'RainToday': 'Yes'}

new_input_df=pd.DataFrame([new_input])

new_input_df

new_input_df[numeric_cols]=imputer.transform(new_input_df[numeric_cols])
new_input_df[numeric_cols]=scaler.transform(new_input_df[numeric_cols])
new_input_df[encoded_cols]=encoder.transform(new_input_df[categorical_cols])

new_input_df

x_new_input=new_input_df[numeric_cols +encoded_cols]
x_new_input

prediction=model.predict(x_new_input)[0]

prediction

def predict_input(single_input):
    input_df = pd.DataFrame([single_input])
    input_df[numeric_cols] = imputer.transform(input_df[numeric_cols])
    input_df[numeric_cols] = scaler.transform(input_df[numeric_cols])
    input_df[encoded_cols] = encoder.transform(input_df[categorical_cols])
    X_input = input_df[numeric_cols + encoded_cols]
    pred = model.predict(X_input)[0]
    prob = model.predict_proba(X_input)[0][list(model.classes_).index(pred)]
    return pred, prob

new_input = {'Date': '2021-06-19',
             'Location': 'Albury',
             'MinTemp': 23.2,
             'MaxTemp': 33.2,
             'Rainfall': 2.2,
             'Evaporation': 4.2,
             'Sunshine': np.nan,
             'WindGustDir': 'NNW',
             'WindGustSpeed': 52.0,
             'WindDir9am': 'NW',
             'WindDir3pm': 'NNE',
             'WindSpeed9am': 13.0,
             'WindSpeed3pm': 20.0,
             'Humidity9am': 89.0,
             'Humidity3pm': 20.0,
             'Pressure9am': 1004.8,
             'Pressure3pm': 1001.5,
             'Cloud9am': 8.0,
             'Cloud3pm': 5.0,
             'Temp9am': 25.7,
             'Temp3pm': 33.0,
             'RainToday': 'Yes'}

predict_input(new_input)

raw_df.Location.unique()

jovian.commit()

import joblib #used for saving the model

aussie_rain = {
    'model': model,
    'imputer': imputer,
    'scaler': scaler,
    'encoder': encoder,
    'input_cols': input_cols,
    'target_col': target_col,
    'numeric_cols': numeric_cols,
    'categorical_cols': categorical_cols,
    'encoded_cols': encoded_cols
}

joblib.dump(aussie_rain, 'aussie_rain.joblib')

aussie_rain2=joblib.load('aussie_rain.joblib')

test_preds2 = aussie_rain2['model'].predict(X_test)
accuracy_score(test_targets, test_preds2)

jovian.commit()

import opendatasets as od
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder

# Download the dataset
od.download('https://www.kaggle.com/jsphyg/weather-dataset-rattle-package')
raw_df = pd.read_csv('weather-dataset-rattle-package/weatherAUS.csv')
raw_df.dropna(subset=['RainToday', 'RainTomorrow'], inplace=True)

# Create training, validation and test sets
year = pd.to_datetime(raw_df.Date).dt.year
train_df, val_df, test_df = raw_df[year < 2015], raw_df[year == 2015], raw_df[year > 2015]

# Create inputs and targets
input_cols = list(train_df.columns)[1:-1]
target_col = 'RainTomorrow'
train_inputs, train_targets = train_df[input_cols].copy(), train_df[target_col].copy()
val_inputs, val_targets = val_df[input_cols].copy(), val_df[target_col].copy()
test_inputs, test_targets = test_df[input_cols].copy(), test_df[target_col].copy()

# Identify numeric and categorical columns
numeric_cols = train_inputs.select_dtypes(include=np.number).columns.tolist()[:-1]
categorical_cols = train_inputs.select_dtypes('object').columns.tolist()

# Impute missing numerical values
imputer = SimpleImputer(strategy = 'mean').fit(raw_df[numeric_cols])
train_inputs[numeric_cols] = imputer.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = imputer.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = imputer.transform(test_inputs[numeric_cols])

# Scale numeric features
scaler = MinMaxScaler().fit(raw_df[numeric_cols])
train_inputs[numeric_cols] = scaler.transform(train_inputs[numeric_cols])
val_inputs[numeric_cols] = scaler.transform(val_inputs[numeric_cols])
test_inputs[numeric_cols] = scaler.transform(test_inputs[numeric_cols])

# One-hot encode categorical features
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoder.fit(raw_df[categorical_cols])

encoded_cols = list(encoder.get_feature_names_out(categorical_cols))

train_inputs[encoded_cols] = encoder.transform(train_inputs[categorical_cols])

# Save processed data to disk
train_inputs.to_parquet('train_inputs.parquet')
val_inputs.to_parquet('val_inputs.parquet')
test_inputs.to_parquet('test_inputs.parquet')
pd.DataFrame(train_targets).to_parquet('train_targets.parquet')
pd.DataFrame(val_targets).to_parquet('val_targets.parquet')
pd.DataFrame(test_targets).to_parquet('test_targets.parquet')

# Load processed data from disk
train_inputs = pd.read_parquet('train_inputs.parquet')
val_inputs = pd.read_parquet('val_inputs.parquet')
test_inputs = pd.read_parquet('test_inputs.parquet')
train_targets = pd.read_parquet('train_targets.parquet')[target_col]
val_targets = pd.read_parquet('val_targets.parquet')[target_col]
test_targets = pd.read_parquet('test_targets.parquet')[target_col]

