# -*- coding: utf-8 -*-
"""RandomForestclassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17a09zVwYUhvcviOIzIaxEVy-V8XiEuB4
"""

import pandas as pd

df=pd.read_excel('/content/Telco_customer_churn.xlsx')

df.head()

df.info()

df = df.drop_duplicates()

df.info()

df.isnull().sum()

df = df.drop(['CustomerID', 'Count'], axis=1, errors='ignore')

print(df.isnull().sum())

import numpy as np
import pandas as pd

num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)## Fill categorical missing values with mode

df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')# Convert TotalCharges to numeric

df['Total Charges'].fillna(df['Total Charges'].median(), inplace=True)#Fill again after conversion

# Convert target column (Churn) to numeric
df['Churn Reason'] = df['Churn Reason'].map({'Yes': 1, 'No': 0})

df = pd.get_dummies(df, drop_first=True)

print(df.shape)

print(df.head())

df.to_csv('cleaned_telco_data.csv', index=False)

import matplotlib.pyplot as plt

df.hist(figsize=(12,10))
plt.show()

X = df.drop('Churn Reason', axis=1)
y = df['Churn Reason']

print(df.isna().sum())

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()

print(df['Churn Reason'].unique())

df['Churn Reason'] = df['Churn Reason'].astype(str)   # convert to string
df['Churn Reason'] = df['Churn Reason'].str.strip()  # remove spaces
df['Churn Reason'] = df['Churn Reason'].str.lower()  # make lowercase

df = df.dropna(subset=['Churn Reason'])

print(df['Churn Reason'].isna().sum())

X = df.drop('Churn Reason', axis=1)
y = df['Churn Reason']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Fix target column properly
target_col = df.columns[-1]

df[target_col] = df[target_col].replace({'Yes':1, 'No':0})

# Remove rows with NaN
df = df.dropna()

# Check values
print(df[target_col].value_counts())

# Split again
X = df.drop(target_col, axis=1)
y = df[target_col]

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

